"""Generate MCP Servers Table - Dummy Script"""

import pathlib


def generate_mcp_table():
    """Generate a dummy MCP servers markdown file."""
    docs_dir = pathlib.Path(__file__).parent.parent
    output_file = docs_dir / "mcp-servers.md"

    content = """# MCP Server Test Results

MCP server test results here

## Test Summary

This is a dummy file generated for testing purposes.

## Last Updated

Generated by GitHub Actions workflow.
"""

    output_file.write_text(content)
    print(f"Generated dummy MCP servers file: {output_file}")


if __name__ == "__main__":
    generate_mcp_table()
