services:
  agent-factory-ui:
    image: node:alpine
    container_name: agent-factory-ui-dev
    working_dir: /agent-factory-ui
    command: sh -c "corepack enable && pnpm install && pnpm dev"
    volumes:
      - .:/agent-factory-ui
      - /agent-factory-ui/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  agent-factory-ui-prod:
    container_name: agent-factory-ui-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod
