name: CI build & push pipeline

on:
  push:
    branches: [ main ]  # Only run on pushes to main
    tags: ["*"]
  workflow_dispatch:

jobs:
  build-push:
    name: Build & push images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'true'
            token: ${{ secrets.GHA_PAT }}

      - name: Truncate commit SHA
        run: echo "GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set image tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            mzdotai/agent-factory:${{ env.IMAGE_TAG }}
            ${{ github.ref_type == 'branch' && github.ref_name == 'main' && 'mzdotai/agent-factory:latest' || '' }}
