name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  run-generation-tests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        prompt_id:
          - summarize-url-content
          - url-to-podcast
          - scoring-blueprints-submission

    steps:
      - name: Check out the repository
        uses: actions/checkout @v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv @v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Run Generation Test - ${{ matrix.prompt_id }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: make test-single-turn-generation PROMPT_ID=${{ matrix.prompt_id }}

  run-agent-evaluation-tests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install Python dependencies
        run: |
          uv sync --group tests

      - name: Run Generated Agent Evaluation tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -v tests/generated_agent_evaluation
