name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  run-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.11
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11
          activate-environment: true

      - name: Install Python dependencies
        run: |
          uv sync --group tests
          uv pip install -e .

      - name: Run Code tests
        run: pytest -v tests/agent_factory

      - name: Run Generation tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -v tests/generation --update-artifacts

      - name: Run Generated Agent Evaluation tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -v tests/generated_agent_evaluation

      - name: Run Generated Artifacts tests
        run: pytest -v tests/generated_artifacts
