name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install Python dependencies
        run: |
          uv sync --group tests
          uv pip install -e .

      - name: Run Code tests
        run: pytest -v tests/agent_factory

      - name: Run Generation unit tests
        run: pytest -v tests/generation/unit

      - name: Run Generated Artifacts tests
        run: |
          pytest tests/generated_artifacts/ -m manufacturing_agent_artifact_validation --prompt-id=summarize-url-content -v
          pytest tests/generated_artifacts/ -m manufacturing_agent_artifact_validation --prompt-id=url-to-podcast -v
          pytest tests/generated_artifacts/ -m manufacturing_agent_artifact_validation --prompt-id=scoring-blueprints-submission -v

  run-tests-requiring-api-key:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install Python dependencies
        run: |
          uv sync --group tests
          uv pip install -e .

      - name: Run Generation Test - Summarize URL Content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest -xvs tests/generation/test_single_turn_generation.py --prompt-id=summarize-url-content

      - name: Run Generation Test - URL to Podcast
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest -xvs tests/generation/test_single_turn_generation.py --prompt-id=url-to-podcast

      - name: Run Generation Test - Scoring Blueprints Submission
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest -xvs tests/generation/test_single_turn_generation.py --prompt-id=scoring-blueprints-submission

      - name: Run Generated Agent Evaluation tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -v tests/generated_agent_evaluation
