name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'eval/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install Python dependencies
        run: |
          uv sync --group tests

      - name: Run Code tests
        run: pytest -v tests/agent_factory

      - name: Run Generation unit tests
        run: pytest -v tests/generation/unit

      - name: Run Generated Artifacts tests
        run: |
          pytest tests/generated_artifacts/ -m manufacturing_agent_artifact_validation --prompt-id=summarize-url-content -v
          pytest tests/generated_artifacts/ -m manufacturing_agent_artifact_validation --prompt-id=url-to-podcast -v
          pytest tests/generated_artifacts/ -m manufacturing_agent_artifact_validation --prompt-id=scoring-blueprints-submission -v

  run-generation-tests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: run-tests
    strategy:
      fail-fast: false
      matrix:
        prompt_id:
          - summarize-url-content
          - url-to-podcast
          - scoring-blueprints-submission

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install Python dependencies
        run: |
          uv sync --group tests

      - name: Run Generation Test - ${{ matrix.prompt_id }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest -xvs tests/generation/test_single_turn_generation.py --prompt-id=${{ matrix.prompt_id }}

  run-agent-evaluation-tests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: run-generation-tests

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install Python dependencies
        run: |
          uv sync --group tests

      - name: Run Generated Agent Evaluation tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -v tests/generated_agent_evaluation
